import type { BlockKind, BlockRole } from '../types'

export type BlockType = {
  kind: BlockKind
  role: BlockRole
  emoji: string
  label: string
  blurb: string
  color: string
  colorSoft: string
}

export const BLOCK_TYPES: Record<BlockKind, BlockType> = {
  taxpayers: {
    kind: 'taxpayers',
    role: 'source',
    emoji: '🧾',
    label: 'Taxpayers',
    blurb: 'Where public money comes from in the first place',
    color: '#64748b',
    colorSoft: '#e2e8f0',
  },
  congress: {
    kind: 'congress',
    role: 'source',
    emoji: '🗳️',
    label: 'Congress',
    blurb: 'Passes the spending bills that hand out the money',
    color: '#1d4ed8',
    colorSoft: '#dbeafe',
  },
  treasury: {
    kind: 'treasury',
    role: 'source',
    emoji: '🏦',
    label: 'U.S. Treasury',
    blurb: 'The nation’s checkbook — it actually sends the money',
    color: '#0369a1',
    colorSoft: '#e0f2fe',
  },
  federal: {
    kind: 'federal',
    role: 'source',
    emoji: '🦅',
    label: 'Federal Agency',
    blurb: 'Big national pot of money',
    color: '#2563eb',
    colorSoft: '#dbeafe',
  },
  state: {
    kind: 'state',
    role: 'source',
    emoji: '🏛️',
    label: 'State Government',
    blurb: 'Statewide funds and budgets',
    color: '#4f46e5',
    colorSoft: '#e0e7ff',
  },
  city: {
    kind: 'city',
    role: 'source',
    emoji: '🏙️',
    label: 'City / Local Gov',
    blurb: 'Your town or county’s money',
    color: '#0891b2',
    colorSoft: '#cffafe',
  },
  tribal: {
    kind: 'tribal',
    role: 'source',
    emoji: '🪶',
    label: 'Tribal Government',
    blurb: 'A sovereign nation that gets funding directly',
    color: '#92400e',
    colorSoft: '#fef3c7',
  },
  schoolDistrict: {
    kind: 'schoolDistrict',
    role: 'source',
    emoji: '🏫',
    label: 'School District',
    blurb: 'Local school money, mostly from property taxes',
    color: '#0f766e',
    colorSoft: '#ccfbf1',
  },
  feeRevenue: {
    kind: 'feeRevenue',
    role: 'source',
    emoji: '🎫',
    label: 'Agency Fees & Fines',
    blurb: 'Money an agency raises itself, not handed to it by Congress',
    color: '#334155',
    colorSoft: '#e2e8f0',
  },
  foundation: {
    kind: 'foundation',
    role: 'source',
    emoji: '💼',
    label: 'Private Foundation',
    blurb: 'Philanthropic giving',
    color: '#9333ea',
    colorSoft: '#f3e8ff',
  },

  grant: {
    kind: 'grant',
    role: 'vehicle',
    emoji: '🎁',
    label: 'Grant',
    blurb: 'Money given for a purpose',
    color: '#16a34a',
    colorSoft: '#dcfce7',
  },
  formulaGrant: {
    kind: 'formulaGrant',
    role: 'vehicle',
    emoji: '📊',
    label: 'Formula Grant',
    blurb: 'Split up by a formula written into the law, like Title I',
    color: '#4d7c0f',
    colorSoft: '#ecfccb',
  },
  blockGrant: {
    kind: 'blockGrant',
    role: 'vehicle',
    emoji: '🧱',
    label: 'Block Grant',
    blurb: 'One flexible lump sum for a broad purpose, like CDBG',
    color: '#15803d',
    colorSoft: '#d1fae5',
  },
  competitiveGrant: {
    kind: 'competitiveGrant',
    role: 'vehicle',
    emoji: '🏆',
    label: 'Competitive Grant',
    blurb: 'You apply against everyone else and the agency picks',
    color: '#047857',
    colorSoft: '#ccfbf1',
  },
  coopAgreement: {
    kind: 'coopAgreement',
    role: 'vehicle',
    emoji: '🪢',
    label: 'Cooperative Agreement',
    blurb: 'Like a grant, but the agency works alongside you',
    color: '#0e7490',
    colorSoft: '#cffafe',
  },
  subgrant: {
    kind: 'subgrant',
    role: 'vehicle',
    emoji: '🧩',
    label: 'Sub-grant',
    blurb: 'A grant passed further along',
    color: '#0d9488',
    colorSoft: '#ccfbf1',
  },
  govContract: {
    kind: 'govContract',
    role: 'vehicle',
    emoji: '📜',
    label: 'Government Contract',
    blurb: 'Paid work for the government',
    color: '#d97706',
    colorSoft: '#fef3c7',
  },
  privContract: {
    kind: 'privContract',
    role: 'vehicle',
    emoji: '🤝',
    label: 'Private Contract',
    blurb: 'A deal between organizations',
    color: '#ea580c',
    colorSoft: '#ffedd5',
  },
  interagency: {
    kind: 'interagency',
    role: 'vehicle',
    emoji: '🔁',
    label: 'Interagency Agreement',
    blurb: 'One government office paying another to do the work',
    color: '#b45309',
    colorSoft: '#fef3c7',
  },
  earmark: {
    kind: 'earmark',
    role: 'vehicle',
    emoji: '📌',
    label: 'Earmark',
    blurb: 'Money Congress points at one named project',
    color: '#be123c',
    colorSoft: '#ffe4e6',
  },
  loan: {
    kind: 'loan',
    role: 'vehicle',
    emoji: '💳',
    label: 'Loan / Guarantee',
    blurb: 'Money that gets paid back, or a promise to cover it',
    color: '#3730a3',
    colorSoft: '#e0e7ff',
  },
  taxCredit: {
    kind: 'taxCredit',
    role: 'vehicle',
    emoji: '🪙',
    label: 'Tax Credit',
    blurb: 'A cut in taxes owed instead of a check, like LIHTC',
    color: '#a16207',
    colorSoft: '#fef9c3',
  },
  voucher: {
    kind: 'voucher',
    role: 'vehicle',
    emoji: '🎟️',
    label: 'Voucher Program',
    blurb: 'Help paid on a person’s behalf, like housing vouchers',
    color: '#6d28d9',
    colorSoft: '#ddd6fe',
  },

  ngo: {
    kind: 'ngo',
    role: 'recipient',
    emoji: '💗',
    label: 'NGO / Nonprofit',
    blurb: 'Mission-driven organization',
    color: '#e11d48',
    colorSoft: '#ffe4e6',
  },
  vendor: {
    kind: 'vendor',
    role: 'recipient',
    emoji: '🏪',
    label: 'Business / Vendor',
    blurb: 'A company doing the work',
    color: '#65a30d',
    colorSoft: '#ecfccb',
  },
  program: {
    kind: 'program',
    role: 'recipient',
    emoji: '🚀',
    label: 'Program / Project',
    blurb: 'Where the work happens',
    color: '#7c3aed',
    colorSoft: '#ede9fe',
  },
  university: {
    kind: 'university',
    role: 'recipient',
    emoji: '🎓',
    label: 'University / Research',
    blurb: 'Campuses and labs doing funded research',
    color: '#c026d3',
    colorSoft: '#fae8ff',
  },
  hospital: {
    kind: 'hospital',
    role: 'recipient',
    emoji: '🏥',
    label: 'Hospital / Clinic',
    blurb: 'Care paid for by public health money',
    color: '#155e75',
    colorSoft: '#cffafe',
  },
  household: {
    kind: 'household',
    role: 'recipient',
    emoji: '🏠',
    label: 'Household',
    blurb: 'One family getting help directly',
    color: '#db2777',
    colorSoft: '#fce7f3',
  },
  community: {
    kind: 'community',
    role: 'recipient',
    emoji: '👥',
    label: 'People / Community',
    blurb: 'Who it all helps',
    color: '#059669',
    colorSoft: '#d1fae5',
  },
}

// Imported JSON reaches the store without its kinds checked against the catalog.
export const blockFor = (kind: BlockKind): BlockType =>
  BLOCK_TYPES[kind] ?? {
    kind,
    role: 'recipient',
    emoji: '❓',
    label: String(kind),
    blurb: 'This block type is not in the catalog',
    color: '#94a3b8',
    colorSoft: '#e2e8f0',
  }

export const PALETTE_GROUPS: { title: string; hint: string; kinds: BlockKind[] }[] = [
  {
    title: 'Where money starts',
    hint: 'Give these a starting pot 💰',
    kinds: [
      'taxpayers',
      'congress',
      'treasury',
      'federal',
      'state',
      'city',
      'tribal',
      'schoolDistrict',
      'feeRevenue',
      'foundation',
    ],
  },
  {
    title: 'How money moves',
    hint: 'Pass money along',
    kinds: [
      'grant',
      'formulaGrant',
      'blockGrant',
      'competitiveGrant',
      'coopAgreement',
      'subgrant',
      'govContract',
      'privContract',
      'interagency',
      'earmark',
      'loan',
      'taxCredit',
      'voucher',
    ],
  },
  {
    title: 'Where money lands',
    hint: 'The good it does',
    kinds: ['ngo', 'vendor', 'program', 'university', 'hospital', 'household', 'community'],
  },
]
