import {
  Blocks,
  Briefcase,
  Building,
  Building2,
  ChartColumn,
  CircleHelp,
  Coins,
  CreditCard,
  Feather,
  FileSignature,
  Flag,
  GraduationCap,
  HandCoins,
  Handshake,
  HeartHandshake,
  Hospital,
  House,
  Landmark,
  Pin,
  ReceiptText,
  Repeat,
  Rocket,
  School,
  Scroll,
  Split,
  Stamp,
  Store,
  Ticket,
  Trophy,
  Users,
  Vote,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import type { BlockKind, BlockRole } from '../types'

export type BlockType = {
  kind: BlockKind
  role: BlockRole
  icon: LucideIcon
  label: string
  blurb: string
  color: string
}

export const BLOCK_TYPES: Record<BlockKind, BlockType> = {
  taxpayers: {
    kind: 'taxpayers',
    role: 'source',
    icon: ReceiptText,
    label: 'Taxpayers',
    blurb: 'Where public money comes from in the first place',
    color: '#64748b',
  },
  congress: {
    kind: 'congress',
    role: 'source',
    icon: Vote,
    label: 'Congress',
    blurb: 'Passes the spending bills that hand out the money',
    color: '#1d4ed8',
  },
  treasury: {
    kind: 'treasury',
    role: 'source',
    icon: Landmark,
    label: 'U.S. Treasury',
    blurb: 'The nation’s checkbook — it actually sends the money',
    color: '#0369a1',
  },
  federal: {
    kind: 'federal',
    role: 'source',
    icon: Building2,
    label: 'Federal Agency',
    blurb: 'Big national pot of money',
    color: '#2563eb',
  },
  state: {
    kind: 'state',
    role: 'source',
    icon: Flag,
    label: 'State Government',
    blurb: 'Statewide funds and budgets',
    color: '#4f46e5',
  },
  city: {
    kind: 'city',
    role: 'source',
    icon: Building,
    label: 'City / Local Gov',
    blurb: 'Your town or county’s money',
    color: '#0891b2',
  },
  tribal: {
    kind: 'tribal',
    role: 'source',
    icon: Feather,
    label: 'Tribal Government',
    blurb: 'A sovereign nation that gets funding directly',
    color: '#92400e',
  },
  schoolDistrict: {
    kind: 'schoolDistrict',
    role: 'source',
    icon: School,
    label: 'School District',
    blurb: 'Local school money, mostly from property taxes',
    color: '#0f766e',
  },
  feeRevenue: {
    kind: 'feeRevenue',
    role: 'source',
    icon: Ticket,
    label: 'Agency Fees & Fines',
    blurb: 'Money an agency raises itself, not handed to it by Congress',
    color: '#334155',
  },
  foundation: {
    kind: 'foundation',
    role: 'source',
    icon: Briefcase,
    label: 'Private Foundation',
    blurb: 'Philanthropic giving',
    color: '#9333ea',
  },

  grant: {
    kind: 'grant',
    role: 'vehicle',
    icon: HandCoins,
    label: 'Grant',
    blurb: 'Money given for a purpose',
    color: '#16a34a',
  },
  formulaGrant: {
    kind: 'formulaGrant',
    role: 'vehicle',
    icon: ChartColumn,
    label: 'Formula Grant',
    blurb: 'Split up by a formula written into the law, like Title I',
    color: '#4d7c0f',
  },
  blockGrant: {
    kind: 'blockGrant',
    role: 'vehicle',
    icon: Blocks,
    label: 'Block Grant',
    blurb: 'One flexible lump sum for a broad purpose, like CDBG',
    color: '#15803d',
  },
  competitiveGrant: {
    kind: 'competitiveGrant',
    role: 'vehicle',
    icon: Trophy,
    label: 'Competitive Grant',
    blurb: 'You apply against everyone else and the agency picks',
    color: '#047857',
  },
  coopAgreement: {
    kind: 'coopAgreement',
    role: 'vehicle',
    icon: Handshake,
    label: 'Cooperative Agreement',
    blurb: 'Like a grant, but the agency works alongside you',
    color: '#0e7490',
  },
  subgrant: {
    kind: 'subgrant',
    role: 'vehicle',
    icon: Split,
    label: 'Sub-grant',
    blurb: 'A grant passed further along',
    color: '#0d9488',
  },
  govContract: {
    kind: 'govContract',
    role: 'vehicle',
    icon: Scroll,
    label: 'Government Contract',
    blurb: 'Paid work for the government',
    color: '#d97706',
  },
  privContract: {
    kind: 'privContract',
    role: 'vehicle',
    icon: FileSignature,
    label: 'Private Contract',
    blurb: 'A deal between organizations',
    color: '#ea580c',
  },
  interagency: {
    kind: 'interagency',
    role: 'vehicle',
    icon: Repeat,
    label: 'Interagency Agreement',
    blurb: 'One government office paying another to do the work',
    color: '#b45309',
  },
  earmark: {
    kind: 'earmark',
    role: 'vehicle',
    icon: Pin,
    label: 'Earmark',
    blurb: 'Money Congress points at one named project',
    color: '#be123c',
  },
  loan: {
    kind: 'loan',
    role: 'vehicle',
    icon: CreditCard,
    label: 'Loan / Guarantee',
    blurb: 'Money that gets paid back, or a promise to cover it',
    color: '#3730a3',
  },
  taxCredit: {
    kind: 'taxCredit',
    role: 'vehicle',
    icon: Coins,
    label: 'Tax Credit',
    blurb: 'A cut in taxes owed instead of a check, like LIHTC',
    color: '#a16207',
  },
  voucher: {
    kind: 'voucher',
    role: 'vehicle',
    icon: Stamp,
    label: 'Voucher Program',
    blurb: 'Help paid on a person’s behalf, like housing vouchers',
    color: '#6d28d9',
  },

  ngo: {
    kind: 'ngo',
    role: 'recipient',
    icon: HeartHandshake,
    label: 'NGO / Nonprofit',
    blurb: 'Mission-driven organization',
    color: '#e11d48',
  },
  vendor: {
    kind: 'vendor',
    role: 'recipient',
    icon: Store,
    label: 'Business / Vendor',
    blurb: 'A company doing the work',
    color: '#65a30d',
  },
  program: {
    kind: 'program',
    role: 'recipient',
    icon: Rocket,
    label: 'Program / Project',
    blurb: 'Where the work happens',
    color: '#7c3aed',
  },
  university: {
    kind: 'university',
    role: 'recipient',
    icon: GraduationCap,
    label: 'University / Research',
    blurb: 'Campuses and labs doing funded research',
    color: '#c026d3',
  },
  hospital: {
    kind: 'hospital',
    role: 'recipient',
    icon: Hospital,
    label: 'Hospital / Clinic',
    blurb: 'Care paid for by public health money',
    color: '#155e75',
  },
  household: {
    kind: 'household',
    role: 'recipient',
    icon: House,
    label: 'Household',
    blurb: 'One family getting help directly',
    color: '#db2777',
  },
  community: {
    kind: 'community',
    role: 'recipient',
    icon: Users,
    label: 'People / Community',
    blurb: 'Who it all helps',
    color: '#059669',
  },
}

// Imported JSON reaches the store without its kinds checked against the catalog.
export const blockFor = (kind: BlockKind): BlockType =>
  BLOCK_TYPES[kind] ?? {
    kind,
    role: 'recipient',
    icon: CircleHelp,
    label: String(kind),
    blurb: 'This block type is not in the catalog',
    color: '#94a3b8',
  }

export const PALETTE_GROUPS: { title: string; hint: string; kinds: BlockKind[] }[] = [
  {
    title: 'Where money starts',
    hint: 'Give these a starting pot',
    kinds: [
      'taxpayers',
      'congress',
      'treasury',
      'federal',
      'state',
      'city',
      'tribal',
      'schoolDistrict',
      'feeRevenue',
      'foundation',
    ],
  },
  {
    title: 'How money moves',
    hint: 'Pass money along',
    kinds: [
      'grant',
      'formulaGrant',
      'blockGrant',
      'competitiveGrant',
      'coopAgreement',
      'subgrant',
      'govContract',
      'privContract',
      'interagency',
      'earmark',
      'loan',
      'taxCredit',
      'voucher',
    ],
  },
  {
    title: 'Where money lands',
    hint: 'The good it does',
    kinds: ['ngo', 'vendor', 'program', 'university', 'hospital', 'household', 'community'],
  },
]
